# KallistiOS ##version##
#
# Addons Makefile.prefab
# Copyright (C)2003 Dan Potter
#   
# $Id: Makefile.prefab,v 1.2 2002/02/09 06:16:00 bardtx Exp $


# KallistiOS addons Makefile include
#
# Define "TARGET", "SUBDIRS" and "OBJS", and then include this file;
# it will handle a lot of your build process. Everything in "OBJS" is
# built by the compiler. If you build everything in subdirs and want to
# just link at the end with this makefile, then define LIB_OBJS as
# something like build/*.o. You'll also want to define LOCAL_CLEAN to
# clean your build dir.

# KOS_AR probably shouldn't work directly into KOS_PATH.

# Include the KOS-specific config for the build arch, if any
-include kos/$(KOS_ARCH).cnf

# install-headers is per-projectly defined

defaultall: install-headers $(OBJS) subdirs linklib

linklib:
	rm -f $(KOS_PATH)/lib/addons/$(TARGET)
	$(KOS_AR) rcs $(KOS_PATH)/lib/addons/$(TARGET) $(OBJS) $(LIB_OBJS)

clean: defaultclean

defaultclean: clean_subdirs
	-rm -f $(OBJS) $(KOS_PATH)/lib/addons/$(TARGET) $(LOCAL_CLEAN)

include $(KOS_PATH)/scripts/Makefile.rules
