TARGET = libbz2.a
OBJS= blocksort.o  \
      huffman.o    \
      crctable.o   \
      randtable.o  \
      compress.o   \
      decompress.o \
      bzlib.o

CFLAGS += -I$(TOPDIR)/include/bzlib

include $(TOPDIR)/Makefile.prefab

