# KallistiOS ##version##
#
# kernel Makefile
# (c)2001 Dan Potter
#   
# $Id: Makefile,v 1.1.1.1 2001/09/26 07:05:09 bardtx Exp $

TARGET = libs3m.a
OBJS = sfxmgr.o
SUBDIRS =

include $(TOPDIR)/Makefile.prefab


