# KallistiOS ##version##
#
# addons/libtremor Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/02/27 04:25:42 bardtx Exp $

TARGET = libtremor.a
OBJS  =
SUBDIRS = xiph kos
LIB_OBJS = build/*.o
LOCAL_CLEAN = build/*.o build/*.a

install-headers:
	@echo Skipping Headers for now...
#	install -d ${KOS_PATH}/include/addons/
#	install -m 660 $(TOPDIR)/include//*.h ${KOS_PATH}/include/addons//


include $(TOPDIR)/Makefile.prefab
