# KallistiOS ##version##
#
# libpcx Makefile
# (c)2002 Dan Potter
#   
# $Id: Makefile,v 1.2 2003/02/27 04:25:42 bardtx Exp $

TARGET = libpcx.a
OBJS = pcx.o

install-headers:
	install -d ${KOS_PATH}/include/addons/pcx
	install -m 660 $(TOPDIR)/include/pcx/*.h ${KOS_PATH}/include/addons/pcx/


include $(TOPDIR)/Makefile.prefab


